import re

batRegex = re.compile(r'Bat(wo)?man')
mo=batRegex.search('The Adventures of Batman')
print(mo.group())
mo=batRegex.search('The Adventures of Batwoman')
print(mo.group())
mo=batRegex.search('The Adventures of Batwowowoman')
print(mo==None)

phoneRegex=re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo=phoneRegex.search('My phone number is 415-555-1234. Call me tomorrow.')
print(mo.group())
mo=phoneRegex.search('My phone number is 555-1234. Call me tomorrow.')
print(mo==None)
phoneRegex=re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')
mo=phoneRegex.search('My phone number is 555-1234. Call me tomorrow.')
print(mo.group())
mo=phoneRegex.search('My phone number is 415-555-1234. Call me tomorrow.')
print(mo.group())

batRegex=re.compile(r'Bat(wo)*man')
mo=batRegex.search('The Adventures of Batman')
print(mo.group())
mo=batRegex.search('The Adventures of Batwoman')
print(mo.group())
mo=batRegex.search('The Adventures of Batwowowoman')
print(mo.group())

batRegex=re.compile(r'Bat(wo)+man')
mo=batRegex.search('The Adventures of Batman')
print(mo==None)
mo=batRegex.search('The Adventures of Batwoman')
print(mo.group())
mo=batRegex.search('The Adventures of Batwowowoman')
print(mo.group())

regex=re.compile(r'\+\*\?')
mo=regex.search('O learned about +*? regex syntax')
print(mo.group())
regex=re.compile(r'(\+\*\?)+')
mo=regex.search('O learned about +*?+*?+*?+*? regex syntax')
print(mo.group())

haRegex = re.compile(r'(Ha){3}')
mo=haRegex.search('He said "HaHaHa"')
print(mo.group())
haRegex = re.compile(r'HaHaHa')
mo=haRegex.search('He said "HaHaHa"')
print(mo.group())

phoneRegex=re.compile(r'((\d\d\d-)?\d\d\d-\d\d\d\d(,)?){3}')
mo=phoneRegex.search('My numbers are 415-5555-1234,555-4242,212-555-0000')
print(mo.group())


haRegex=re.compile(r'(Ha){3,5}')
mo=haRegex.search('He said "HaHaHa"')
print(mo.group())
mo=haRegex.search('He said "HaHaHaHa"')
print(mo.group())
mo=haRegex.search('He said "HaHaHaHaHa"')
print(mo.group())

digitRegex=re.compile(r'(\d){3,5}')
mo=digitRegex.search('1234567890')
print(mo.group())
digitRegex=re.compile(r'(\d){3,5}?')
mo=digitRegex.search('1234567890')
print(mo.group())
